# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dizfp2RQYpYuH6DVPb5XeR4mDo7NhlGh
"""

from fastapi import FastAPI, File, UploadFile
import torch
from torchvision import transforms
from PIL import Image
import io
import torch.nn as nn
from fastapi.middleware.cors import CORSMiddleware
# Import CNN class
#from model import CNN   # or paste class here
import torch.nn as nn

app = FastAPI(title = "MNIST CNN API")

#Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

from fastapi import FastAPI, File, UploadFile
import torch
from torchvision import transforms
from PIL import Image
import io
import torch.nn as nn
from fastapi.middleware.cors import CORSMiddleware
# Import CNN class
from model import CNN   # or paste class here
import torch.nn as nn

app = FastAPI(title = "MNIST CNN API")

#Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================
# CNN MODEL DEFINITION
# =========================
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2)

        self.conv2 = nn.Conv2d(32, 64, kernel_size=3)

        self.fc1 = nn.Linear(64 * 5 * 5, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = x.view(x.size(0), -1)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# =========================
# FASTAPI INITIALIZATION
# =========================
#app = FastAPI(title="MNIST CNN API")

# =========================
# LOAD MODEL
# =========================
model = CNN()
model.load_state_dict(
    torch.load("mnist_cnn_weights.pth", map_location=torch.device("cpu"))
)
model.eval()

# =========================
# IMAGE TRANSFORM
# =========================
transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# =========================
# ROUTES
# =========================

@app.get("/")
def home():
    return {"message": "MNIST CNN API is running 🚀"}

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    # Read image
    image_bytes = await file.read()
    image = Image.open(io.BytesIO(image_bytes)).convert("L")

    # Preprocess
    image = transform(image).unsqueeze(0)

    # Prediction
    with torch.no_grad():
        output = model(image)
        probabilities = torch.softmax(output, dim=1)
        confidence, predicted = torch.max(probabilities, 1)

    return {
        "predicted_digit": int(predicted.item()),
        "confidence": float(confidence.item())
    }

# =========================
# RUN (optional)
# =========================
# Run using terminal:
# uvicorn app:app --reload
